[buildPlans.iosevka-nf]
family = "Iosevka nf Custom"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
#no-ligation = true # not needed with fixed spacing?

  [buildPlans.iosevka-nf.variants]
  inherits = "ss04"

  [buildPlans.iosevka-nf.variants.design]
  zero = "dotted"

[collectPlans.iosevka-nf]
from = ["iosevka-nf"]
